### ISSUE TITLE
Decide on (and document) GitHub permissions system for our organization

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/leadership#1]
_This is a topic to discuss at a future team meeting._

Tasks that this should probably be broken down into:
- Review how GitHub permissions works
- Make sure everyone on our team understands how GitHub permissions work
- Outline a list of our choices in how to handle permissions for our group here
- Discuss and decide as a group
- Document result of our decision in a place easy to find for future reference

Relevant documentation from GitHub on how permissions work:
https://help.github.com/articles/permission-levels-for-an-organization/
https://help.github.com/categories/setting-up-and-managing-organizations-and-teams/

**Comment by ghost** [comment]
This is a great issue. I'm completely new to Git and would like to become very proficient. I'll search some of these ideas and prepare them for the 10/27 meeting

**Comment by ghost** [comment]
Here's what I was going to present at the meeting but ran out of time (New to git, so lemme know if there's a better way to share this): 

Review how GitHub permissions works: 
_Current default permission setup seems reasonable._ 

Make sure everyone on our team understands how GitHub permissions work:
_Most important differences seem to be 1) Billing, 2) Creating/Manipulating Teams/Communities. Basically Members can do anything involving the projects but CANNOT access billing or invite new members. Billing/Membership should be up to a select few in leadership (according to GitHub recommendation)._ 

Outline a list of our choices in how to handle permissions for our group here:
_Billing should be one to two people at most? (Organizer, Billing)
Everyone else can have Member status with maybe more options to manipulate projects (Member)
If Leadership member or LtCLA community wants more control over a project, he/she should open separate Git account? With independent billing/management._ 

(Note: Will need to look into how one can have Manager or Organizer permissions with separate projects within one Git account, ie. can someone have Organizer permissions for one project but NOT Organizer permissions on another project? I guess this will depend on how many/complex the projects become.)
