### ISSUE TITLE
January 31st Learn to Code LA 2nd year anniversary party or hackathon?

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/leadership#16]
Would be fun to celebrate, and also make use of the nice venues we now have access to! A celebration and show-and-tell night would be fun, or if we're feeling really ambitious it might be fun to do a hackathon the weekend before or after (Jan 28th/29th or Jan 4th/5th), but if we do, it would require plenty of advance planning -- like starting in November.

**Comment by armaneous** [comment]
So... hackathon?! 😃

**Comment by rouzbeh84** [comment]
Sorry, I should have updated here as well. 

I reached out to Codepen for another sponsored meetup and they were interested as well as Pivotal Labs to host in Santa Monica so we have a big venue!

We were discussing the format in addition to some lightning talks but possibly a 'State of Group' talk led by Liz and some other cool demos. I read recently that a Codepen meetup in Brazil went very long so I don't think we need to limit our time frame to anything outside of what PL is offering to donate haha

**Comment by LearningNerd** [comment]
This is happening! A show-and-tell night / anniversary party combo. :) Gonna close this issue though since the planning is happening via private communication and Slack now.
