### ISSUE TITLE
Change our organization's name! (Add your suggestions and thoughts here before our final vote)

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/leadership#19]
**Let's pick a new name for our organization!**

**Update 12/14/16:** I emailed the final vote form to everyone, so let me know if you didn't get it! (Keep the form link private so only our team can see it.) Feel free to continue the discussion here. **Deadline to fill out the form to vote is Monday Dec 19th, 2016.**

**Guidelines for good names:**
- The name should sound professional, but also fun and friendly sounding. It should be easy to spell and easy to remember. And of course it should capture the essence of what we're doing, if possible!
- The domain name (or something very similar to the name at least) should still be available, either .org or .com or ideally both
- Ideally, the name should still be available on GitHub and social media. If not, a similar name should be available; like if LearnTeachCode is taken, LearnTeachCodeORG should at least be free.
- The name should be something we can trademark easily (see https://www.uspto.gov/trademarks-getting-started/trademark-basics), so something not already taken and something not too generic
- Key words to help with name ideas: code, programming, learn, education, social, community, friendly, fun, welcoming, beginner-friendly, connecting people, free, global, world, tech, tech literacy, creative, projects, study groups, collective, coalition, co-op, fellowship, commons, .... **[suggest more!]**

**Why change our name?:**
- We have a Learn to Code Seoul group run by @TheBeege, and @x2adrew expressed interest in starting a group in Seattle, so the name "Learn to Code LA" clearly doesn't work anymore!
- And "Learn to Code" on its own isn't ideal because: 1) the domain name is already taken, 2) it's difficult to trademark since it's pretty generic as a name (see #17), and 3) it may already be trademarked by another group.
- Plus I was never crazy about the name anyway; I picked it on a whim with no planning or research and I never thought this group would grow to be such an active community!

**Next steps after we decide on the new name:** 
- Outline a plan for the how to roll out the change and update our domain name and meetup name and github and slack and social media accounts without confusing people too much!
- Announce it to our whole community beforehand, followed by another announcement once the change is made.
- Jump into our branding, logo design, website design and all that fun stuff once we have our new name, and the celebrate it at our 2-year anniversary party on January 31, 2017!

**Comment by TheBeege** [comment]
Name suggestion: Get Programming
See https://github.com/LearnToCodeLA/leadership/issues/17#issuecomment-256823968

**Comment by TheBeege** [comment]
Learn Programming may also be a good alternative. The domain is purchased, but it has an individual's information. There is no website at the domain. Seems to be a squatter maybe...?

**Comment by TheBeege** [comment]
https://www.google.com/trends/explore?q=learn%20programming,learn%20to%20code,get%20programming
Learn programming seems to be the heavy hitter. Good news is that learnprogramming.io appears to be open.

According to the US Patent and Trademark Office, "learn programming" has no marks on it.

I'm realizing we may not want to place terribly much value on having a heavy-hitting name right out the gate, since codecademy and whatnot show up as similar terms in Google. If we do good work, whatever we decide to name ourselves may rise up on its own merit.

**Comment by TheBeege** [comment]
@LearningNerd what criteria are we looking to meet before we pull the trigger? We should probably create an issue on how to carry out the rename, as well. I imagine there are quite a few things tied to the name at this point. I'll keep looking up names

**Comment by TheBeege** [comment]
howtocode.org is registered but isn't working due to bad configuration. This suggests it isn't parked so much as unused. Unfortunately, there's a privacy company registered in whois. May be difficult contacting the actual owner. 

How to Code does not appear to be in the USPTO database.

Aaaaaand I just realized you're looking for a less generic sounding name. I'll ponder more

**Comment by TheBeege** [comment]
My notes are below the ='s. Here are a bunch of names I think may be viable. They all are available as .org domains and are not registered in the USPTO database. If any of these sound appealing, I can do a deeper dive

cosmitto (Latin - connect/construct)
llunio (Welsh - construct/form)
criari (Corsican - create)
abuuro (Somalian - create)
coducation

Thoughts?

# 

Coding Community
Codemunity is taken -_- I thought that was kind clever. I'm a little sad now.
Educode is taken

I tried some Latin words, translations of create, make, build, construct... I found erigo, which is "erect, raise, set up, rise, lift, construct." erigo.org is not taken... but Erigo is registered with the trademark office

Conficio is taken by some Russian dude

cosmitto.org is not taken, and cosmitto does not appear to be trademarked. It's Latin for for "bring together, engage, set against, Unite, connect, construct," which actually seems to fit really, really, really nicely I think. It doesn't quite roll off the tongue, though.

Switched to Welsh. Found some interesting things.

llunio.org is not taken and llunio is not trademarked. It means "form, design, construct, fashion"

Not a whole lot else in Welsh that's both available and easy to spell.

From Corsican, criari.org is not taken and has no trademark. It literally means create.

From Somalian, abuuro is available. Also literally means create.

**Comment by TheBeege** [comment]
Tech Education Collective! 
(Then the Sins of a Solar Empire fans can have the TEC empire they've always dreamed of xD)

Tech Education Fellowship could be interesting, but it has an academic air to it. 

Tech Education Commons actually sounds pretty solid. I feel like "commons" has a non-profit connotation

**Comment by LearningNerd** [comment]
The results of more time than I'd like to admit spent researching, here are a few more that I really like:
- **Learn Teach Code** -- I just bought the .org, not trademarked, github name available, but it's taken on twitter/FB. I really like this one though!
- **Curious Coders** -- I just bought the .org, not trademarked, FB and Twitter available, but taken on GitHub
- **Code Curious** -- I just bought the .org, and the .com is available but expensive ($1895 per year?! O_o), not trademarked.
- Code Collective -- .org available
- Code Social -- .org available

And here are a couple more that I liked but their domain names are taken:
- Social Coding
- Code Commons
- Code the World

But certainly we could recombine elements from any of the previously suggested names, or just tack on the word Foundation at the end to grab the domain name or GitHub username. Stuff like:
- Social Coding Collective
-  Learn Teach Code Foundation
- Curious Coders Collective
- etc

**Comment by armaneous** [comment]
Sorry for arriving so late to this. Some great ideas in here! I'm a little split on the two approaches @TheBeege and @LearningNerd have taken. I like the idea of reaching into other languages for that catchy, one-word name - but I also like the idea of keeping it limited to basic English... I need to spend some more time doing research on this.

**Comment by johnmarinelli** [comment]
my vote goes to `Curious Coding Collective` or `Curious Coders`. BC INQUISITIVENESS FTW

**Comment by sevilturner** [comment]
How about these names:

- Promise of a Keystroke
- One line at a time
- Code Passionately
- More than code
- Software enthusiasts

I will do a research on the domain names and get back to you soon.

**Comment by ykcab** [comment]
We should also prioritize a Brand name that define both as an Learning entity as well as a non profit organization.
Think something inspiring ( i.e 8th lights: simple, elegant,makes you think and forces you to know more...)

**Comment by colin-m-b** [comment]
buildinguptocode.com is available and might be easy to remember, although it might not reflect what the group is actually meant for.

learnbuildrepeat.com is also available, but might be too vague since it doesn't mention coding.

groundfloorcode is available in any format.

@LearningNerd I like codesocial.org, but there's a Code Social meetup group. It's based in Leeds, UK, though, so I don't know if that would be a problem.

**Comment by TheBeege** [comment]
I know both Liz and I are partial to Learn Teach Code, but there's the social media conflict... For both Twitter and Facebook, I'm aware that the username is distinct from the display name. Would it be possible to have our display name as "Learn Teach Code" but our username something like "learn.teach.code"? Is there still a unique constraint on display names?

**Comment by jbazalar** [comment]
A few ideas:
letsgocode.org (.com n/a)
letsgocode.club
devthecode.org
devthecode.com
codedocent.com
codedocent.org
thecodeeffect.org (.com n/a)
codetumble.org
codetumble.com

**Comment by TheBeege** [comment]
I know both Liz and I are partial to Learn Teach Code, but there's the social media conflict... For both Twitter and Facebook, I'm aware that the username is distinct from the display name. Would it be possible to have our display name as "Learn Teach Code" but our username something like "learn.teach.code"? Is there still a unique constraint on display names?

**Comment by rouzbeh84** [comment]
I like learnteachcode or....

![image](https://cloud.githubusercontent.com/assets/1803843/21057752/b8739ad0-bdef-11e6-8629-14b388a3b018.png)

**Comment by LearningNerd** [comment]
Thanks all for the suggestion so far! Keep em coming, and feel free to argue in favor of or against any of them. I personally am still very partial to Learn Teach Code or Curious Coders (Collective/Commons/Foundation/etc) myself, hehe

@rouzbeh84 somehow Teach Learn Code is waayy harder for my brain to remember, I dunno why. I guess a priming effect from our current name Learn to Code (same acronym as Learn Teach Code), or logically my mind people learn before they teach. I dunno.

@TheBeege We can absolutely have a display name like Learn Teach Code and a different username like @learn.teach.code or @learnteachcodeHQ or @learnteachcodeORG etc etc. That's very common; for example, CodeNewbie.org uses @codenewbies on Twitter and GitHub because the singular form was already taken. Lots of other organizations do the same.

**Comment by armaneous** [comment]
Learn Teach Code can work, though I can't help but imagine a delimiter of some sort (coma or period) between each word when I think of the name. It looks so awkward otherwise.

I tend to lean more towards hidden meaning than in-your-face branding, particularly if we can reduce it to 1-2 words with at most two syllables total. @TheBeege was sort of exploring that already with other languages and I'm partial to Greek because of their historical pursuit of philosophy and wisdom. If that's something we're open to exploring, sophi (sophia, -sophy, sophi-) is Greek for wisdom if anyone wants to play with that, but I recognize that's probably going to go against the original statement of limiting syllables.

Anyway, these are just my immediate thoughts. Don't have any worthwhile suggestions on names at the moment, I'll post if I think of anything.

**Comment by ghost** [comment]
I'll just throw mine out there: **codopoly**. It's available as a .com. I like the **c, o, d, p, l, y** look. Would be a graphic designer's dream word. But I'm happy to cast my vote for whatever Liz decides for her short list.

**Comment by armaneous** [comment]
@jgstr I really like that, though I first read it as **codeploy** for some reason. Which, honestly, I also like. It could be read as both co-deploy (pair programming, cooperation, always creating) and code ploy (playful code, masterminding code to take over the world).

In the same vein is the unique order of consonants that, without vowels, would be immediately recognizable to us: **c, d, p, l, y**.

**Comment by ykcab** [comment]
@jgstr I like that too : **codepoly**. oops not sure why i first said codeploy; as @x2adrew explained. I love it for the sense of it behind totally unique of a creativity, collaboration, and it will open us lot of ideas on designing the logo. which will be much much flexible. 

- codepoly.org ($8.99)
- codepoly.com (No info)
- codepoly.net ($8.85)
- and many more

**Comment by armaneous** [comment]
I also just realized that the consonants alone could be _codeplay_, which also sounds like another good name. I'm really liking the look of just the consonants. Why don't we just go with **cdply** (in the same token of SQL pronounced as _sequel_)?

**Comment by ykcab** [comment]
@x2adrew then we can forge to CDPLY Foundation, I like it.

**Comment by armaneous** [comment]
Credit goes to @jgstr since I really just took his idea and modified it.

**Comment by LearningNerd** [comment]
@x2adrew @ykcab @jgstr Codopoly or Codepoly looks and sounds cool, and I think it's a great name in and of itself, but for some reason it really throws me off as a name for our community =/ I've been trying to identify why exactly, and I guess to me it feels like the name of a startup company or a product more than a community. It also sounds very techie, which I associate with less inclusive groups for some reason.

This brought up something I never noticed before: groups for promoting more diversity in tech (one of our big goals!) tend to have more straightforward and plain names , and seem much less likely to be based on clever/short word combinations. Like there's [Code as a Second Language](http://www.loftcsl.org/), [Black Girls Code](http://www.blackgirlscode.com/), [Girl Develop It](https://www.girldevelopit.com/), [Society of Hispanic Professional Engineers](http://www.shpe.org/), [Lesbians Who Tech](http://lesbianswhotech.org/)... There are plenty of exceptions to this "rule" of course! I might be completely wrong here; I have no hard data to support it. Just my subjective experience.

Anyway, I'd love to hear more feedback from everyone on their pros and cons for the names already suggested here! Debate and discussion is more important than a simple vote tally. I'll share more of my thoughts in the next couple of days here too.

**Comment by TheBeege** [comment]
I really like cdply but not necessarily for the learning/teaching aspect of our group. Maybe we could use that name for a projects subdivision? Maybe a sub-group that creates/supports open source projects? Or that codes for other non-profit organizations. However, such a thing is a discussion for another thread ^_^

Just wanted to voice support for the idea but applying it somewhere other than the education-focused org.

**Comment by sevilturner** [comment]
How about these names that are focused on people and community versus just technology.

1. Code with Community
2. Build Code and Community
3. Community for Techies
4. Everyone gets a chance
5. Learn, build, mentor

**Comment by ykcab** [comment]
@LearningNerd I am completely in the same view. Having a name that explain of itself. Though we would want to focus as a community, we are a complex and mix of active members/visitors, branding our community with an explicit Brand Name might a complex challenge.
We can have an implicit Brand Name and our Logo does the Explicit definition of it - just another approach to tackle.

@TheBeege your idea is not that bad at all. We can apply that one too.
Looking at @sevilturner ^^ comments - We have to consider SE (Search Engine) results too. Got some plenty, interesting and weird results using those suggestions. Not saying they are bad but we will have to work hard on our SEO (Search Engine Optimization) infiltration.

**Comment by LearningNerd** [comment]
Thanks for the additional suggestions @sevilturner! Thanks @ykcab, good points!

Well I didn't send out the shortlist like I said I would on Monday but I just sent it out now, so **you should all have an email from me with a link to the google form to vote**. Let me know if you didn't get it though. Keep the link private so that only our leadership team can see it. Thanks!

And like I said, feel free to make the case for or against any name(s) you feel strongly about, or feel free to argue with me about the shortlist I chose, haha.

**Comment by LearningNerd** [comment]
The vote has concluded, with a majority for Learn Teach Code. Thank you everyone for the good feedback! I'll send out an email as well. Next steps are the actual changing of the name, see issue #26: [Complete the Learn Teach Code name change](https://github.com/LearnToCodeLA/leadership/issues/26) Any and all feedback is appreciated as always!
