### ISSUE TITLE
How to best serve the members of LTCLA

### ISSUE THREAD

**Issue by colin-m-b** [LearnTeachCode/leadership#23]
We touched on it a little bit tonight, but I think we should try to identify the types of members who are part of the group and how they can best be served. 

I'm guessing there are 4 main types:

1: Complete beginners: people who don't know html and are mostly just curious at this point. They might be overwhelmed by the amount of info/resources online and don't know where to start.

2: Hobbyists: people who want to build a personal or business site, or who just like playing around and making cool webpages. They don't need to understand public and private classes, or the prototype chain in JavsScript. 

3: People looking to start a career: these are probably people who have some skills, but want to level up. They might be prepping for a bootcamp, or are hoping to get a job in the field in the near future, and need help getting over that chasm between beginner and intermediate.

4: People ready to work or already working in the industry: These members probably want to learn something new (language, framework, etc), or want to give back and be part of the group for the community aspect.

So meetups like the drawing app that @LearningNerd did recently would mostly be geared towards groups 2 and 3, with some 4s there too. Maybe every month or two, there could be a meetup targeting group 1, an Intro to HTML class. I can't remember who mentioned it, but a meetup on Git would be great for the 3s and 4s. Maybe there could be a Build a Site For Your Business class that would help out the 1s and 2s.

I mention this mostly so we can think of how to balance things to make sure everyone is able to benefit. Also, if we're going to write grant proposals, we'll need to have specific programs in mind that the money will fund, and this might help organize our thinking about that.

**Comment by rouzbeh84** [comment]
Do you mean having some sort of 'level' legend for each meetup so potential participants can decide whether its for them or not?

**Comment by armaneous** [comment]
I think it'd be great if we get more people from group 4 to help out in some capacity with the lower-numbered groups.

**Comment by TheBeege** [comment]
I really like this breakdown @colin-m-b. I think it covers just about everyone.

I think @rouzbeh84's suggestion of a level legend is an alright idea, but given that we don't have a strong static content presence, I imagine the meaning may be lost. Then again, we could do something like, "This is for <level>, see <link> for more info."

This essentially gets into understanding your audience territory. Which of these groups do most of our members fall into? What's the cross-over like? What types of events are each group interested in? Which group do we, as an organization, want to focus our efforts on?

When it comes to establishing large initiatives, like the mentor program, the above questions would be helpful in tailoring the program. How many mentors would we need? How effort do we want to invest in the program based on how many members fit into the target group(s)? Should training for mentors be different depending on the mentee's group?

We could also use it to create large initiatives. Like @x2adrew's comment, if we feel like we need more people from group 4 to help out, we can come up with a new initiative to recruit those people.

I really, really like this idea. I've seen user categorization used at companies I've worked at, and it is immensely helpful in focusing your efforts. We can either use attendance tracking or surveys to identify categorizations.

**Comment by colin-m-b** [comment]
@rouzbeh84 I wasn't thinking of labeling our meetups with a legend, more just things to keep in mind as we plan. For example, if we notice that attendance is going down, or that we aren't getting many new members, we might look at what meetups we've been running lately and realize we've only been catering to one type of member. I think labeling might discourage people from attending if they feel they aren't in the right group.

**Comment by rouzbeh84** [comment]
True, just a suggestion. We have so many diff meetups I don't think it would exclude too many and since most of our meetups are casual gatherings of people coding maybe labelling is a bad idea after all. I think the  biggest challenge is that it is on meetup.com and people treat meetup very ephemerally in that rsvp'ing means almost nothing haha.

**Comment by TheBeege** [comment]
Mmm, yeah I like it as an internal planning tool. No need to make it public. Most companies follow a similar approach. 
In my head, I categorize people in the Seoul meetup, as well. It's useful for targeting specific content and knowing where I need to spend more time on things.
