### ISSUE TITLE
Leadership meeting #2 recap and next action items [draft]

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/leadership#24]
**In a couple days I'll finalize this draft and email it to everyone on our leadership team along with a link to the private video recording. Feel free to add suggestions, critiques, etc!**

Recap: Learn to Code LA Leadership Meeting #2 
October 27th, 2016

**Attendees:**
- list of everyone's names and slack usernames here

**Discussion points:**
- any main themes, questions raised
- The main takeaway from this meeting was probably just that we all finally got to see each others' faces! That plus the realization that our leadership team is really enormous now!

**Next steps:**
- Add any ideas or questions as a GitHub issue at https://github.com/LearnToCodeLA/leadership/issues
- Help us set up small working groups so that our next meetings will be more productive! :) Take a look at the GitHub issues and if you want to get more involved in helping with a particular task, write a comment on that task to let us know.

**Comment by armaneous** [comment]
Are we going to do a leadership meeting on some sort of regular schedule? I think that'd be awesome, though it might have to wait until after the holidays.

We did have a pretty large turnout last time, so maybe it's impractical to include *all* of the leadership, team. Unsure of how to tackle that part, though.

**Comment by TheBeege** [comment]
We could setup committees. We could have a general meet - I imagine Liz giving a general "state of the meetup" and an indication of next priorities. Following that, we could break off into smaller topic groups - name change, non-profit, mentoring, courses, sponsorship, etc etc

**Comment by LearningNerd** [comment]
@x2adrew @TheBeege  I like the idea of doing sprints for completing specific tasks, with a working group/committee for each, and then those smaller groups would decide for themselves how often their regular meetings should be.

As for larger leadership meetings, I'm leaning towards just sending out a blurb with updates for everyone ("state of the meetup" sounds fun, haha) and _not_ doing a huge meeting again, unless it's primarily just for socializing. But after the holidays I do want to at least plan a meeting for the study group leaders, which is just a few of us. And anyone else is welcome to suggest a call to a meeting if there's a need for one.

**Comment by armaneous** [comment]
I like the committee thing, as bureaucratic as it is, just because it gives everyone the mobility to be as involved as they like without holding the overall leadership responsible for attending things.
