### ISSUE TITLE
Machine Learning study group (Led by Sina and John M)

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/leadership#25]
Sina (@agenttuy) and John (@johnmarinelli) are interested in starting a machine learning group, but have this problem to solve:

"I gave out a form to get a sense of who were all interested. So far, it seems like mostly beginners to machine learning are interested. I’m wondering if machine learning is compatible with Learn to Code LA? Most of machine learning implies some prerequisite knowledge (in higher math, intermediate with a language). I’m not sure how to make this beginner-friendly OR how to attract intermediate to advanced machine learning folks to Learn to Code LA. I’ll need some input on how to get this going. John Marinelli has offered to help me host/lead this group as well." -- _quote from Sina on our last sync-up on October 27 2016._

**Comment by agenttuy** [comment]
Maybe this group could start out theoretical? Speak of concepts, history, and maybe even philosophy? I remember before John M. got interested in machine learning, I had to convince him of its practicality by arguing statistics and philosophy. Maybe that'll be fun for beginners!?

And also, I definitely want to guide/lead this group with John's help but I'm definitely looking for someone to host this meetup if it becomes a meetup group. I think a beginner as a host would be great. Many people who've signed up for the group so far have expressed interest in hosting.
